services:
  rr-front-local:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        VITE_API_URL: "http://localhost:8080/api"
        VITE_FRONT_VERSION: "dev-local"
    container_name: rr-front-local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      rr-api-local:
        required: true
        condition: service_healthy

  rr-api-local:
    image: ghcr.io/infcdaal1/rr:dev
    container_name: rr-api-local
    ports:
      - "8080:80"
    environment:
      DB_HOST: rr-db-local
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env
    depends_on:
      rr-db-local:
        required: true
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80/up || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 15

  rr-db-local:
    image: 'mariadb:11'
    container_name: rr-db-local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'rr_db_local:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  rr_db_local:
    driver: local

networks:
  db:
    name: db-local
