services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        VITE_API_URL: "http://localhost:8080/api"
        VERSION: "dev-local"
    container_name: front-local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      api:
        required: true
        condition: service_healthy

  api:
    image: ghcr.io/infcdaal1/rr-vue:dev
    container_name: api-local
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env
    depends_on:
      db:
        required: true
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/v1/version || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: 'mariadb:11'
    container_name: db_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mariadb:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  db_local:
    driver: local

networks:
  db:
    name: db-local
