/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/core/AppBar.vue')['default']
    AppFooter: typeof import('./components/core/AppFooter.vue')['default']
    CategoryCard: typeof import('./components/category/CategoryCard.vue')['default']
    CategoryForm: typeof import('./components/category/CategoryForm.vue')['default']
    CategoryList: typeof import('./components/category/CategoryList.vue')['default']
    CommentCard: typeof import('./components/comment/CommentCard.vue')['default']
    CommentList: typeof import('./components/comment/CommentList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InvitationCard: typeof import('./components/invitation/InvitationCard.vue')['default']
    InvitationForm: typeof import('./components/invitation/InvitationForm.vue')['default']
    InvitationList: typeof import('./components/invitation/InvitationList.vue')['default']
    MessageDetail: typeof import('./components/message/MessageDetail.vue')['default']
    MessageGroupCard: typeof import('./components/message/MessageGroupCard.vue')['default']
    MessageList: typeof import('./components/message/MessageList.vue')['default']
    MessageNewConversation: typeof import('./components/message/MessageNewConversation.vue')['default']
    NavBar: typeof import('./components/core/NavBar.vue')['default']
    NotFound: typeof import('./components/core/NotFound.vue')['default']
    ProfilCard: typeof import('./components/profile/ProfilCard.vue')['default']
    ProfilForm: typeof import('./components/profile/ProfilForm.vue')['default']
    ResourceCard: typeof import('./components/resource/ResourceCard.vue')['default']
    ResourceForm: typeof import('./components/resource/ResourceForm.vue')['default']
    ResourceList: typeof import('./components/resource/ResourceList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeArea: typeof import('./components/core/SafeArea.vue')['default']
    StepConfirmation: typeof import('./components/auth/register/StepConfirmation.vue')['default']
    StepForgotPassword: typeof import('./components/auth/forgot/StepForgotPassword.vue')['default']
    StepSendEmail: typeof import('./components/auth/forgot/StepSendEmail.vue')['default']
    StepSetPassword: typeof import('./components/auth/register/StepSetPassword.vue')['default']
    StepUserInfo: typeof import('./components/auth/register/StepUserInfo.vue')['default']
    VListProfile: typeof import('./components/profile/VListProfile.vue')['default']
  }
}
