/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/core/AppBar.vue')['default']
    AppFooter: typeof import('./components/core/AppFooter.vue')['default']
    Auth: typeof import('./components/auth/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index: typeof import('./components/auth/index.vue')['default']
    NavBar: typeof import('./components/core/NavBar.vue')['default']
    NotFound: typeof import('./components/core/NotFound.vue')['default']
    ResourceCard: typeof import('./components/resource/ResourceCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepForgotPassword: typeof import('./components/auth/forgot/StepForgotPassword.vue')['default']
    StepSendEmail: typeof import('./components/auth/forgot/StepSendEmail.vue')['default']
    StepSetPassword: typeof import('./components/auth/register/StepSetPassword.vue')['default']
    StepUserInfo: typeof import('./components/auth/register/StepUserInfo.vue')['default']
    VListProfile: typeof import('./components/profile/VListProfile.vue')['default']
  }
}
