/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/forgot/': RouteRecordInfo<'/auth/forgot/', '/auth/forgot', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register/': RouteRecordInfo<'/auth/register/', '/auth/register', Record<never, never>, Record<never, never>>,
    '/category/': RouteRecordInfo<'/category/', '/category', Record<never, never>, Record<never, never>>,
    '/category/add/': RouteRecordInfo<'/category/add/', '/category/add', Record<never, never>, Record<never, never>>,
    '/category/edit/[id]': RouteRecordInfo<'/category/edit/[id]', '/category/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/invitation/': RouteRecordInfo<'/invitation/', '/invitation', Record<never, never>, Record<never, never>>,
    '/message/': RouteRecordInfo<'/message/', '/message', Record<never, never>, Record<never, never>>,
    '/message/[id]': RouteRecordInfo<'/message/[id]', '/message/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/privacy/': RouteRecordInfo<'/privacy/', '/privacy', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/[id]': RouteRecordInfo<'/profile/[id]', '/profile/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profile/add/': RouteRecordInfo<'/profile/add/', '/profile/add', Record<never, never>, Record<never, never>>,
    '/profile/edit/[id]': RouteRecordInfo<'/profile/edit/[id]', '/profile/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/resource/': RouteRecordInfo<'/resource/', '/resource', Record<never, never>, Record<never, never>>,
    '/resource/[id]': RouteRecordInfo<'/resource/[id]', '/resource/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/resource/add/': RouteRecordInfo<'/resource/add/', '/resource/add', Record<never, never>, Record<never, never>>,
    '/resource/edit/[id]': RouteRecordInfo<'/resource/edit/[id]', '/resource/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/resource/favorite/': RouteRecordInfo<'/resource/favorite/', '/resource/favorite', Record<never, never>, Record<never, never>>,
    '/stats/': RouteRecordInfo<'/stats/', '/stats', Record<never, never>, Record<never, never>>,
  }
}
