/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/page2': RouteRecordInfo<'/admin/page2', '/admin/page2', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/forgot/': RouteRecordInfo<'/auth/forgot/', '/auth/forgot', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register/': RouteRecordInfo<'/auth/register/', '/auth/register', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/resource/': RouteRecordInfo<'/resource/', '/resource', Record<never, never>, Record<never, never>>,
    '/resource/[id]': RouteRecordInfo<'/resource/[id]', '/resource/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/resource/favorite/': RouteRecordInfo<'/resource/favorite/', '/resource/favorite', Record<never, never>, Record<never, never>>,
  }
}
