name: Build All (Docker + Android)

on:
  push:
    branches:
      - main
      - dev

jobs:
  trigger_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_docker.yml
          ref: ${{ github.ref_name }}

      - name: Trigger Android build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_android.yml
          ref: ${{ github.ref_name }}
