name: Build All (Docker + Android)

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  audit:
    name: Audit npm Dependencies
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

  build-android:
    name: Build Android App
    needs: [ lint, audit ]
    runs-on: ubuntu-latest
    concurrency:
      group: build-android-${{ github.ref }}
      cancel-in-progress: true

    env:
      NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      VITE_API_URL: ${{ github.ref == 'refs/heads/main' && 'https://rr-api.qalpuch.cc/api' || 'https://rr-api.qalpuch.cc/api' }}
      # Variables pour la signature et le versioning
      KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set version name
        run: |
          if [ "${{ env.NODE_ENV }}" = "production" ]; then
            echo "VERSION_NAME=prod-${{ steps.vars.outputs.SHORT_SHA }}" >> $GITHUB_ENV
          else
            echo "VERSION_NAME=dev-${{ steps.vars.outputs.SHORT_SHA }}" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: NODE_ENV=development npm ci

      - name: Build web app
        run: npm run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          VITE_API_URL: ${{ env.VITE_API_URL }}
          VERSION: ${{ env.VERSION_NAME }}

      - name: Add Android folder if not present
        run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Create Keystore file from secret
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > release.jks
          echo "KEYSTORE_PATH=$(pwd)/release.jks" >> $GITHUB_ENV

      - name: Capacitor sync
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: "22"
          cache: 'gradle'

      - name: Build Android App
        run: |
          cd android
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

      - name: List built files
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            ls -lh ./android/app/build/outputs/apk/release
          else
            ls -lh ./android/app/build/outputs/apk/debug
          fi

      - name: Cleanup Keystore
        run: rm -f release.jks

      - name: APK Release Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed.apk
          path: ./android/app/build/outputs/apk/release/app-release-signed.apk

      - name: APK Debug Artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

  build-docker:
    name: Build Docker Image
    needs: [ lint, audit ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
      REGISTRY: ghcr.io
      IMAGE_NAME: infcdaal1/rr-vue
      VITE_API_URL: ${{ github.ref == 'refs/heads/main' && 'https://rr-api.qalpuch.cc/api' || 'https://rr-api.qalpuch.cc/api' }}

    concurrency:
      group: build-docker-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set image tags
        run: |
          if [ "${{ env.NODE_ENV }}" = "production" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
            echo "VERSION=prod-${{ steps.vars.outputs.SHORT_SHA }}" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
            echo "VERSION=dev-${{ steps.vars.outputs.SHORT_SHA }}" >> $GITHUB_ENV
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: production
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            VITE_API_URL=${{ env.VITE_API_URL }}
            VERSION=${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max